gcc -o Compiler.exe LexicalAnalyzer.h SyntaxAnalyzer.c LexicalAnalyzer.c
#Compiler.exe: SyntaxAnalyzer.o LexicalAnalyzer.o
#	gcc -o Compiler.exe LexicalAnalyzer.o SyntaxAnalyzer.o
#
#LexicalAnalyzer.o: LexicalAnalyzer.c LexicalAnalyzer.h
#	gcc -o LexicalAnalyzer.o LexicalAnalyzer.c
#
#SyntaxAnalyzer.o: SyntaxAnalyzer.c
#	gcc -o SyntaxAnalyzer.o SyntaxAnalyzer.c